name       : luarocks
version    : 3.3.1
release    : 2
source     :
    - https://github.com/luarocks/luarocks/archive/v3.3.1.tar.gz : 837481e408f7c06b59befe7ec194537c657687d624894bca7f79034302141a34
license    : MIT
component  : programming
summary    : The package manager for the Lua programming language
description: |
    It allows you to install Lua modules as self-contained packages called rocks, which also contain version dependency information. This information can be used both during installation, so that when one rock is requested all rocks it depends on are installed as well, and also optionally at run time, so that when a module is required, the correct version is loaded. LuaRocks supports both local and remote repositories, and multiple local rocks trees.
builddeps  :
    - pkgconfig(lua-5.3)
rundeps    :
    - lua-devel
setup      : |
    ./configure --prefix=/usr \
        --sysconfdir=/etc/luarocks \
        --lua-version=5.3 \
        --with-lua-include=/usr/include \
build      : |
    %make
install    : |
    %make_install
