name       : luarocks
version    : 3.8.0
release    : 5
source     :
    - https://github.com/luarocks/luarocks/archive/refs/tags/v3.8.0.tar.gz : ab6612ca9ab87c6984871d2712d05525775e8b50172701a0a1cabddf76de2be7
license    : MIT
homepage   : https://luarocks.org/
component  : programming
summary    : The package manager for the Lua programming language
description: |
    Luarocks allows you to install Lua modules as self-contained packages called rocks, which also contain version dependency information. This information can be used both during installation, so that when one rock is requested all rocks it depends on are installed as well, and also optionally at run time, so that when a module is required, the correct version is loaded. LuaRocks supports both local and remote repositories, and multiple local rocks trees.
builddeps  :
    - pkgconfig(lua-5.3)
rundeps    :
    - lua-devel
setup      : |
    ./configure --prefix=/usr \
        --sysconfdir=/etc/luarocks \
        --lua-version=5.3 \
        --with-lua-include=/usr/include \
build      : |
    %make
install    : |
    %make_install
